### ISSUE TITLE
Validity of SingleR with very small bulk RNAseq reference

### ISSUE THREAD

**Issue by nickhir** [SingleR-inc/SingleR#273]
Hello,

I am currently working with a single cell dataset from a frog colon and would like to estimate the origin of the cells (i.e. the region of the colon). There exists a dataset that has performed bulk RNAseq of the 8 different colon sections. 

My idea is to use this dataset to predict the origin of my single cells. The only issue is, that I only have access to 8 samples (each corresponding to one colon section). My question is, if it is still valid to use SingleR in that case, or if the sample size of the reference is too small. I noticed that in the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/SingleR/inst/doc/SingleR.html) the size of your reference dataset was much bigger (>700).

Any help is much appreciated!

**Comment by LTLA** [comment]
I'd say it's probably fine. Or more specifically, there's not much else you can do.

Our reference datasets have multiple samples per label to account for heterogeneity within each label, e.g., "T cell" covers a wide range of things, so we want multiple samples to represent helper cells, cytotoxic cells, etc. This ensures that our cell type assignment has a chance to match to an appropriate reference rather than some imaginary "average T cell".

Recall that SingleR works by computing Spearman's rank correlation between each reference sample and each cell.  SingleR will use only the largest 20% (default) of correlations to derive its assignment score for each label, ensuring that we focus on matches to the relevant subtypes and are not overly penalized for intra-label heterogeneity.

If you don't expect a lot of heterogeneity, then there's not much need to get multiple samples. If you do expect heterogeneity, then you should get a more comprehensive reference... Of course, the only way to know if you should expect heterogeneity is to understand your biological system, at which point you probably have more samples.

**Comment by nickhir** [comment]
Brilliant, thank you very much for your input!
